### ISSUE TITLE
Sensors stop working

### ISSUE THREAD

**Issue by danbuhler** [michaeldavie/flume-sensor#2]
I get this error every so often requiring me to delete flume_tokens:

```
2019-07-26 13:13:58 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform flume
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/flume/sensor.py", line 41, in setup_platform
    CONF_CLIENT_SECRET: config.get(CONF_CLIENT_SECRET)
  File "/config/custom_components/flume/flume_homeassistant.py", line 35, in __init__
    self.get_device_id()
  File "/config/custom_components/flume/flume_homeassistant.py", line 62, in get_device_id
    self.device_id = [d['id'] for d in response['data'] if d['type'] == 2][0]
IndexError: list index out of range
```

**Comment by danbuhler** [comment]
I'm still getting this quite often with the newest version. I'm not sure what triggers the sensors to stop working.

```
2019-08-07 16:06:32 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform flume
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/flume/sensor.py", line 41, in setup_platform
    CONF_CLIENT_SECRET: config.get(CONF_CLIENT_SECRET)
  File "/config/custom_components/flume/flume_homeassistant.py", line 44, in __init__
    self.device_id = [d['id'] for d in response['data'] if d['type'] == 2][0]
IndexError: list index out of range
```

**Comment by danbuhler** [comment]
These errors seem directly related to how often I restart Home Assistant. The deleting the tokens file doesn't seem to help or make the problem worse.

Is there anything happening at startup that could be causing flume to throttle or have some other error?

How can I grab any debug data to send you?

**Comment by trashcan** [comment]
This happened to me as well, and the error was ust happening over and over to where HomeAssistant never finished starting up. I'm also happy to provide any debug information.

**Comment by mcondren** [comment]
Same here. Works some of the time, not others.

**Comment by jaburges** [comment]
any news on this?

**Comment by niharmehta** [comment]
Same problem here. Works for a few hours then stops updating. Restarting HA brings it back for a bit until it stops.
